FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia la solución y todos los archivos de proyecto
COPY . . 

# Restaura las dependencias de toda la solución
RUN dotnet restore

# Publica el proyecto principal (ApiPrueba)
RUN dotnet publish "ApiPrueba/ApiPrueba.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 80
ENTRYPOINT ["dotnet", "ApiPrueba.dll"]